version: 1.7.{build}
image: Visual Studio 2017
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
test_script:
- cmd: >-
    "%APPVEYOR_BUILD_FOLDER%\packages\xunit.runner.console.2.1.0\tools\xunit.console.x86.exe" "%APPVEYOR_BUILD_FOLDER%\artifacts\TorSharp\TorSharp.Tests\bin\Debug\Knapcode.TorSharp.Tests.dll" -appveyor

    "%APPVEYOR_BUILD_FOLDER%\packages\xunit.runner.console.2.1.0\tools\xunit.console.exe" "%APPVEYOR_BUILD_FOLDER%\artifacts\TorSharp\TorSharp.Tests\bin\Debug\Knapcode.TorSharp.Tests.dll" -appveyor
