//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AServiceAgent
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/AServiceContract")]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool EnabledField;
        
        private int IdField;
        
        private int LimitField;
        
        private string NameField;
        
        private AServiceAgent.Position PosField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Enabled
        {
            get
            {
                return this.EnabledField;
            }
            set
            {
                this.EnabledField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Limit
        {
            get
            {
                return this.LimitField;
            }
            set
            {
                this.LimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AServiceAgent.Position Pos
        {
            get
            {
                return this.PosField;
            }
            set
            {
                this.PosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Position", Namespace="http://schemas.datacontract.org/2004/07/AServiceContract")]
    public partial class Position : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateField;
        
        private string DirectField;
        
        private int PriceField;
        
        private int SizeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direct
        {
            get
            {
                return this.DirectField;
            }
            set
            {
                this.DirectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Size
        {
            get
            {
                return this.SizeField;
            }
            set
            {
                this.SizeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogMessage", Namespace="http://schemas.datacontract.org/2004/07/AServiceContract")]
    public partial class LogMessage : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MessageField;
        
        private string SourceField;
        
        private AServiceAgent.LogMessage.MessageType TypField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AServiceAgent.LogMessage.MessageType Typ
        {
            get
            {
                return this.TypField;
            }
            set
            {
                this.TypField = value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="LogMessage.MessageType", Namespace="http://schemas.datacontract.org/2004/07/AServiceContract")]
        public enum MessageType : int
        {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Warn = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Error = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Fatal = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Info = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Debug = 4,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AServiceAgent.AlarmServer", CallbackContract=typeof(AServiceAgent.AlarmServerCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface AlarmServer
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/AlarmServer/DetectPosition")]
        void DetectPosition();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/AlarmServer/ChangePosition")]
        void ChangePosition(int size, string direct, int price, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/AlarmServer/ConnectOperator")]
        void ConnectOperator();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/AlarmServer/DisconnectOperator")]
        void DisconnectOperator();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlarmServer/CancelLastSignal", ReplyAction="http://tempuri.org/AlarmServer/CancelLastSignalResponse")]
        bool CancelLastSignal(bool decision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlarmServer/GetAccounts", ReplyAction="http://tempuri.org/AlarmServer/GetAccountsResponse")]
        AServiceAgent.Account[] GetAccounts();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface AlarmServerCallback
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/AlarmServer/AlertNewSignal")]
        void AlertNewSignal(AServiceAgent.Position pos);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/AlarmServer/UpdateUIAccount")]
        void UpdateUIAccount(AServiceAgent.Account account);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/AlarmServer/ServerLogMessages")]
        void ServerLogMessages(AServiceAgent.LogMessage log);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface AlarmServerChannel : AServiceAgent.AlarmServer, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AlarmServerClient : System.ServiceModel.DuplexClientBase<AServiceAgent.AlarmServer>, AServiceAgent.AlarmServer
    {
        
        public AlarmServerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance)
        {
        }
        
        public AlarmServerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName)
        {
        }
        
        public AlarmServerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }
        
        public AlarmServerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }
        
        public AlarmServerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress)
        {
        }
        
        public void DetectPosition()
        {
            base.Channel.DetectPosition();
        }
        
        public void ChangePosition(int size, string direct, int price, System.DateTime date)
        {
            base.Channel.ChangePosition(size, direct, price, date);
        }
        
        public void ConnectOperator()
        {
            base.Channel.ConnectOperator();
        }
        
        public void DisconnectOperator()
        {
            base.Channel.DisconnectOperator();
        }
        
        public bool CancelLastSignal(bool decision)
        {
            return base.Channel.CancelLastSignal(decision);
        }
        
        public AServiceAgent.Account[] GetAccounts()
        {
            return base.Channel.GetAccounts();
        }
    }
}
